export default async function handler(req, res) {
  const answers = [
    "Yes",
    "No",
    "Maybe",
    "Definitely",
    "Absolutely",
    "Absolutely not",
    "Without a doubt",
    "I doubt it",
    "Ask again later",
    "Reply hazy try again",
    "Signs point to yes",
    "Signs point to no",
    "The vibes say yes",
    "The vibes are cursed",
    "Very sus but yes",
    "Very sus but no",
    "That is a bad idea",
    "That is a great idea",
    "Do it for the plot",
    "Main character moment",
    "NPC behavior detected",
    "Side quest unlocked",
    "Boss fight soon",
    "Secret ending unlocked",
    "Error 404 answer not found",
    "System malfunction",
    "The universe is buffering",
    "Destiny says yes",
    "Destiny says no",
    "Destiny took a nap",
    "My lawyer says no",
    "Legally I cant answer",
    "Yes but risky",
    "No but tempting",
    "Flip a coin",
    "Even Google does not know",
    "Ask chat",
    "Ask your dog",
    "Touch grass first",
    "Drink water first",
    "Eat first then ask",
    "Luck too low",
    "Luck maxed out",
    "Skill issue",
    "Massive skill issue",
    "God tier play",
    "Chaos says yes",
    "Chaos says run",
    "Classified information",
    "Redacted",
    "Plot twist incoming",
    "Villain arc begins",
    "Hero arc unlocked",
    "Character development moment",
    "Lore says yes",
    "Lore says no",
    "This will be iconic",
    "This will be cringe",
    "Stream clip moment",
    "Chat will remember this",
    "Mods are nervous",
    "Mods approve",
    "Probability high",
    "Probability low",
    "RNG says suffer",
    "RNG says lucky",
    "The algorithm favors you",
    "The algorithm hates you",
    "Future you says yes",
    "Future you says no",
    "Past you disagrees",
    "Reality is optional",
    "Simulation says yes",
    "Simulation glitch maybe",
    "Multiverse approved",
    "Multiverse denied",
    "Risk level extreme",
    "Safe choice",
    "Risky but fun",
    "Mission failed successfully",
    "Achievement unlocked bad decision",
    "Achievement unlocked bold move",
    "Green light",
    "Red light",
    "Yellow light",
    "Vibes check passed",
    "Vibes check failed",
    "Signal strong",
    "Signal lost",
    "Energy says go",
    "Energy says stop",
    "The stars say yes",
    "The stars say no",
    "The prophecy agrees",
    "The prophecy says no",
    "Outcome spicy",
    "Outcome boring",
    "Plot armor says yes",
    "Plot armor expired",
    "You rolled a natural one",
    "You rolled a natural twenty",
    "Confidence high",
    "Confidence zero",
    "Permission granted",
    "Permission denied",
    "Access granted",
    "Access blocked",
    "Try again tomorrow",
    "Now is the time",
    "Not the time",
    "Send it",
    "Hold back",
    "Bro just wing it",
    "This is a canon event",
    "You cant stop this event",
    "Certified bruh moment",
    "Emotional damage incoming",
    "This unlocks trauma",
    "This unlocks lore",
    "Side character energy",
    "Main villain energy",
    "Hero training arc begins",
    "You are built different",
    "Aint no way",
    "Lowkey yes",
    "Highkey no",
    "Touching this will start a war",
    "This is above your rank",
    "You are not him",
    "You are him",
    "Go outside bro",
    "This is content",
    "The script says yes",
    "The script says no",
    "W decision",
    "L decision",
    "Huge W",
    "Huge L",
    "NPCs are judging",
    "The council approves",
    "The council said no",
    "The voices say yes",
    "The voices say run",
    "Trust the process",
    "Trust issues detected",
    "This feels illegal",
    "This feels right",
    "Speedrun strat",
    "Bad ending unlocked",
    "Good ending unlocked"
  ];

  const randomAnswer = answers[Math.floor(Math.random() * answers.length)];
  return new Response(randomAnswer);
}
